#
# CMake4Mbed
# https://github.com/grbd/GBD.Embedded.CMake4Mbed

# TODO Eventually this file will be auto generated by the Visual Studio project files
# via an app I've yet to write

# All Project specific values are below

# The name of the project
project (HelloWorld-LPC)

# A macro to collect local sources into ${SRCS}.
# This variable gets propagated to the parent scope and is ultimately used in
# the top-level CMakeLists.txt to define the dependencies for the build target.
#
# Files within this list are relative to the current folder.
# Please also note that this macro must be used at all CMakeLists.txt files at
# intermediate levels even if the list is empty--this is due to the Cmake magic
# involved in propagating variables to only the parent scope.
add_sources(
    src/main.cpp
	src/gcc4mbed.cpp
)

# Set the Output to a <ProjectName>.elf file
set(PROJECT_ELF ${PROJECT_NAME}.elf)
message(STATUS "Project elf target : ${PROJECT_ELF}")

add_executable(${PROJECT_ELF} ${SRCS})



#message(STATUS "SRCS: ${SRCS}")

# TODO use the util script to output .hex / .bin files from the .elf
