PROJECT         := HelloWorld-STM32
DEVICES         := NUCLEO_F103RB
GCC4MBED_DIR    := ../../
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1
GCC4MBED_TYPE   := Release
MRI_ENABLE      := 0

include $(GCC4MBED_DIR)/oldmake/gcc4mbed.mk
